#include <core/io/layouts/english.hpp>
#include <core/kernel.hpp>

using namespace std;
using namespace system::core::io;
using namespace system::core::io::layouts;

english::english()
: _specials_right(
    {
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ESC } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '1' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '2' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '3' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '4' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '5' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '6' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '7' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '8' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '9' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '-' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '=' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\b' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\t' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'q' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'w' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'e' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'r' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 't' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'y' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'u' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'i' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'o' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::NEXT_TRACK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '[' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ']' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\n' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CTRL_R } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'a' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 's' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::MUTE } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CALC } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::PLAY } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'h' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::STOP } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'k' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'l' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ';' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\'' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '`' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\\' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'z' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'x' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::VOL_DW } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'v' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::VOL_UP } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'n' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::HOME } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ',' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '.' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '/' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_R } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ALT_R } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ALT_R } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ' ' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CPSLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F1 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F2 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F3 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F4 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F5 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F6 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F7 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F8 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F9 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F10} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::NUMLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::HOME } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CUR_UP } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::PG_UP } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '9' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CUR_LF } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '4' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CUR_RG } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '6' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::END } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CUR_DW } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::PG_DW } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::INSERT } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CANC } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '.' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F11} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F12} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::GUI_LF} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::GUI_RG} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::APPS} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::POWER} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SLEEP} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::WAKE} },
    }
  ),
  _layout(
    {
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ESC } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '1' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '2' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '3' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '4' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '5' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '6' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '7' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '8' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '9' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '-' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '=' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\b' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\t' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'q' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'w' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'e' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'r' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 't' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'y' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'u' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'i' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'o' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'p' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '[' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ']' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\n' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CTRL_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'a' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 's' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'd' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'f' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'g' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'h' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'j' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'k' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'l' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ';' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\'' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '`' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\\' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'z' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'x' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'c' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'v' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'b' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'n' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'm' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ',' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '.' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '/' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_R } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '*' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ALT_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ' ' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CPSLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F1 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F2 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F3 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F4 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F5 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F6 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F7 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F8 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F9 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F10} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::NUMLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SCRLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '7' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '8' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '9' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '-' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '4' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '5' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '6' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '+' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '1' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '2' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '3' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '.' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F11} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F12} },
    }
  ),
  _layout_sft(
    {
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ESC } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '!' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '@' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '#' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '$' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '%' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '^' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '&' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '*' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '(' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ')' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '_' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '+' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\b' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\t' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'Q' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'W' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'E' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'R' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'T' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'Y' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'U' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'I' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'O' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'P' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '{' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '}' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\n' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CTRL_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'A' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'S' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'D' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'F' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'G' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'H' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'J' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'K' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'L' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ':' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '"' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '~' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '|' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'Z' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'X' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'C' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'V' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'B' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'N' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'M' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '<' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '>' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '?' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_R } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '*' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ALT_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ' ' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CPSLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F1 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F2 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F3 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F4 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F5 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F6 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F7 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F8 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F9 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F10} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::NUMLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SCRLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '7' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '8' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '9' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '-' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '4' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '5' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '6' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '+' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '1' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '2' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '3' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '.' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F11} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F12} },
    }
  ),
  _layout_alt_gr(
    {
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ESC } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '!' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '@' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '#' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '$' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '%' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '^' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '&' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '*' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '(' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ')' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '_' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '+' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\b' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\t' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'Q' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'W' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'E' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'R' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'T' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'Y' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'U' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'I' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'O' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'P' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '{' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '}' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\n' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CTRL_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'A' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'S' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'D' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'F' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'G' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'H' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'J' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'K' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'L' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ':' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '"' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '~' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '|' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'Z' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'X' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'C' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'V' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'B' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'N' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'M' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '<' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '>' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '?' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_R } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '*' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ALT_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ' ' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CPSLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F1 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F2 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F3 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F4 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F5 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F6 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F7 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F8 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F9 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F10} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::NUMLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SCRLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '7' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '8' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '9' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '-' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '4' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '5' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '6' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '+' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '1' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '2' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '3' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '.' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F11} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F12} },
    }
  ),
  _layout_ctrl_gr(
    {
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ESC } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '!' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '@' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '#' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '$' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '%' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '^' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '&' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '*' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '(' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ')' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '_' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '+' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\b' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\t' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'Q' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'W' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'E' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'R' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'T' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'Y' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'U' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'I' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'O' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'P' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '{' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '}' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\n' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CTRL_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'A' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'S' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'D' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'F' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'G' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'H' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'J' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'K' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'L' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ':' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '"' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '~' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '|' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'Z' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'X' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'C' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'V' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'B' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'N' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = 'M' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '<' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '>' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '?' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SFT_R } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '*' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::ALT_L } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = ' ' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::CPSLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F1 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F2 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F3 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F4 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F5 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F6 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F7 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F8 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F9 } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F10} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::NUMLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::SCRLK } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '7' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '8' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '9' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '-' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '4' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '5' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '6' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '+' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '1' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '2' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '3' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '.' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::NORMAL, .data = { .character = '\0' } },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F11} },
        key_t { .focus = focus_t::PRESS, .type = keytype_t::SPECIAL, .data = { .special = special_t::F12} },
    }
  )
{
}

key_t english::scan(system::hal::drivers::kb::scancode_t code, array<std::special_t> &combination, bool right)
{
    if (combination.size() == 1)
    {
        if (combination[0] == special_t::SFT_L || combination[0] == special_t::SFT_R)
        {
            key_t r;
            if (!right) r = _layout_sft[code.key];
            else r = _specials_right[code.key];
            r.focus = (focus_t)code.release;
            return r;
        }
        else if (combination[0] == special_t::ALT_R)
        {
            key_t r = _layout_alt_gr[code.key];
            r.focus = (focus_t)code.release;
            return r;
        }
    }
    else if (combination.size() == 2)
    {
        if ((combination[0] == special_t::ALT_R && combination[1] == special_t::CTRL_R) || (combination[0] == special_t::CTRL_R && combination[1] == special_t::ALT_R))
        {
            key_t r;
            if (!right) r = _layout_sft[code.key];
            else r = _specials_right[code.key];
            r.focus = (focus_t)code.release;
            return r;
        }
    }
    
    key_t r = _layout[code.key];
    if (!right) r = _layout[code.key];
    else r = _specials_right[code.key];
    r.focus = (focus_t)code.release;

    return r;
}